DESIRED_PLATFORMS = set([
    'List_of_32X_games',
    'List of ColecoVision games',
    'List of Family Computer games',
    'List of Atari ST games',
    'List of PlayStation Move games',
    'List_of_Magnavox_Odyssey²_games',
    'List of Nintendo DS games',
    'List of Sega CD games',
    'List of Amiga CD32 games',
    'List of Game Gear games',
    'List of Family Computer Disk System games',
    "List_of_Xbox_360_games",
    'List of Wii U games',
    'List of Kaypro games',
    'List of Master System games',
    'List of Virtual Console games for Wii (Japan)',
    'Index_of_DOS_games_(0–9)',
    'Index_of_DOS_games_(A)',
    'Index_of_DOS_games_(B)',
    'Index_of_DOS_games_(C)',
    'Index_of_DOS_games_(D)',
    'Index_of_DOS_games_(E)',
    'Index_of_DOS_games_(F)',
    'Index_of_DOS_games_(G)',
    'Index_of_DOS_games_(H)',
    'Index_of_DOS_games_(I)',
    'Index_of_DOS_games_(J)',
    'Index_of_DOS_games_(K)',
    'Index_of_DOS_games_(L)',
    'Index_of_DOS_games_(M)',
    'Index_of_DOS_games_(N)',
    'Index_of_DOS_games_(O)',
    'Index_of_DOS_games_(P)',
    'Index_of_DOS_games_(Q)',
    'Index_of_DOS_games_(R)',
    'Index_of_DOS_games_(S)',
    'Index_of_DOS_games_(T)',
    'Index_of_DOS_games_(U)',
    'Index_of_DOS_games_(V)',
    'Index_of_DOS_games_(X)',
    'Index_of_DOS_games_(Y)',
    'Index_of_DOS_games_(Z)',
    'Index_of_Windows_games_(0–9)',
    'Index_of_Windows_games_(A)',
    'Index_of_Windows_games_(B)',
    'Index_of_Windows_games_(C)',
    'Index_of_Windows_games_(D)',
    'Index_of_Windows_games_(E)',
    'Index_of_Windows_games_(F)',
    'Index_of_Windows_games_(G)',
    'Index_of_Windows_games_(H)',
    'Index_of_Windows_games_(I)',
    'Index_of_Windows_games_(J)',
    'Index_of_Windows_games_(K)',
    'Index_of_Windows_games_(L)',
    'Index_of_Windows_games_(M)',
    'Index_of_Windows_games_(N)',
    'Index_of_Windows_games_(O)',
    'Index_of_Windows_games_(P)',
    'Index_of_Windows_games_(Q)',
    'Index_of_Windows_games_(R)',
    'Index_of_Windows_games_(S)',
    'Index_of_Windows_games_(T)',
    'Index_of_Windows_games_(U)',
    'Index_of_Windows_games_(V)',
    'Index_of_Windows_games_(X)',
    'Index_of_Windows_games_(Y)',
    'Index_of_Windows_games_(Z)',
    'List of arcade video games',
    'List of Atari XEGS games',
    'List of HP3000 games',
    'List_of_Game_Boy_games',
    'List of Xbox 360 games',
    'List of Amstrad PCW games',
    'List of Super Nintendo Entertainment System games',
    'List of Xbox Live Arcade games',
    'List of N-Gage games',
    'List_of_3DO_Interactive_Multiplayer_games',
    'List of PlayStation 2 games',
    'List_of_Game_%26_Watch_games',
    'List of Virtual Console games for Wii U (Japan)',
    'List of GameCube games',
    'List of Xbox Originals',
    'List_of_Xbox_games_on_Windows_Phone',
    'List of Linux games',
    'List of Super Famicom games',
    'List_of_PlayStation_Vita_games_(A–L)',
    'List_of_PlayStation_Vita_games_(M–Z)',
    'List of FM Towns games',
    'List of SAM Coupé games',
    'List of Atari Lynx games',
    'List of Virtual Console games for Wii U (North America)',
    'List of Virtual Console games for Wii (North America)',
    'List of Virtual Console games for Nintendo 3DS (PAL region)',
    'List of Game Boy Color games',
    'List of Vectrex games',
    'List of Neo-Geo Pocket Color games',
    'List of Virtual Console games for Nintendo 3DS (North America)',
    'List of Atari Jaguar games',
    'List of Apple IIGS games',
    'List_of_downloadable_Xbox_360_games',
    'List_of_PC_Engine_games',
    'List of Xbox One games',
    'List_of_PlayStation_games_(A–L)',
    'List_of_PlayStation_games_(M–Z)',
    'List of Virtual Console games for Nintendo 3DS (Japan)',
    'List of Nintendo 3DS games',
    'List of Games for Windows titles',
    'List_of_Windows_3.x_games',
    'List of DSiWare games and applications',
    'List of Atari 7800 games',
    'List of Nintendo Entertainment System games',
    'List of TurboGrafx-16 games',
    'List of PlayStation Portable games',
    'List of Macintosh games',
    'List of iOS games',
    'List of Amstrad CPC games',
    'List of Virtual Console games for Wii (PAL region)',
    'List of ZX Spectrum games',
    'List of Game Boy Advance games',
    'List of PlayStation 4 games',
    'List_of_PlayStation_4_games_(M-Z)',
    'List of PC Engine games',
    'List of Sony Pictures mobile games',
    'List of Nintendo Switch games',
    'List of Xbox games',
    'List_of_Neo_Geo_games',
    'List_of_Ouya_software',
    'List_of_Sega_Genesis_games',
    'List of MSX games',
    'List of CD-i games',
    'List of Gizmondo games',
    'List of TRS-80 games',
    'List_of_Amiga_games_(A–H)',
    'List_of_Amiga_games_(I–O)',
    'List_of_Amiga_games_(P–Z)',
    'List of Commodore VIC-20 games',
    'List of Acorn Electron games',
    'List of WonderSwan games',
    'List of Atari 2600 games',
    'List_of_Sega_Saturn_games',
    'List of Games for Windows – Live titles',
    'List_of_Commodore_64_games_(A–M)',
    'List_of_Commodore_64_games_(N–Z)',
    'List of Virtual Boy games',
    'List of WonderSwan Color games',
    'List_of_PC_booter_games',
    'List of PC games',
    'List_of_PC_games_(B)',
    'List_of_PC_games_(C)',
    'List_of_PC_games_(D)',
    'List_of_PC_games_(E)',
    'List_of_PC_games_(F)',
    'List_of_PC_games_(G)',
    'List_of_PC_games_(H)',
    'List_of_PC_games_(I)',
    'List_of_PC_games_(J)',
    'List_of_PC_games_(K)',
    'List_of_PC_games_(L)',
    'List_of_PC_games_(M)',
    'List_of_PC_games_(N)',
    'List_of_PC_games_(O)',
    'List_of_PC_games_(P)',
    'List_of_PC_games_(Q)',
    'List_of_PC_games_(R)',
    'List_of_PC_games_(S)',
    'List_of_PC_games_(T)',
    'List_of_PC_games_(U)',
    'List_of_PC_games_(V)',
    'List_of_PC_games_(X)',
    'List_of_PC_games_(Y)',
    'List_of_PC_games_(Z)',
    'List_of_PC_games_(Numerical)',
    'List of Nintendo 64 games',
    'List of Apple II games',
    'List of Intellivision games',
    'List of Dreamcast games',
    'List of commercial GP32 games',
    'List of Windows Games on Demand',
    'List of WiiWare games',
    'List of Virtual Console games for Wii U (PAL region)',
    'List of PC-FX games',
    'List_of_PlayStation_3_games_released_on_disc',
    'List_of_download-only_PlayStation_3_games',
    'List of Wii games',
    'List of Atari 5200 games'
])


# scrap article outcome
class ArticleOutcome:
    FOUND_NOT = -1
    FOUND_UAT = 0
    FOUND_ASSERTIVE = 1


ARTICLE_OUTCOME_DISPLAY = {
    ArticleOutcome.FOUND_NOT: "FOUND_NOT",
    ArticleOutcome.FOUND_UAT: "FOUND_UAT",
    ArticleOutcome.FOUND_ASSERTIVE: "FOUND_ASSERTIVE",
}


class UnassertiveArticle:
    CROSS_MEDIA_ARTICLE = 1
    GAME_SERIES_ARTICLE = 2

UAT_DISPLAY = {
    UnassertiveArticle.CROSS_MEDIA_ARTICLE: "Cross-Media Article",
    UnassertiveArticle.GAME_SERIES_ARTICLE: "Game-Series Article",
}
