"""Self explanatory."""

NEW_LISTS = [
    'List_of_Acorn_Electron_games',
    'List_of_Apple_II_games',
    'List_of_Apple_IIGS_games',
    'List_of_iOS_games',
    'List_of_Macintosh_games',
    'List_of_Amstrad_CPC_games',
    'List_of_Amstrad_PCW_games',
    'List_of_Atari_2600_games',
    'List_of_Atari_7800_games',
    'List_of_Atari_Jaguar_games',
    'List_of_Atari_Lynx_games',
    'List_of_Atari_ST_games',
    'List_of_Atari_XEGS_games',
    'List_of_WonderSwan_games',
    'List of Game Boy games',
    'List_of_WonderSwan_Color_games',
    'List_of_Amiga_games_(A–H)',
    'List_of_Amiga_games_(I–O)',
    'List_of_Amiga_games_(P–Z)',
    'List_of_Amiga_CD32_games',
    'List_of_Commodore_64_games_(A–M)',
    'List_of_Commodore_64_games_(N–Z)',
    'List_of_Commodore_VIC-20_games',
    'List_of_FM_Towns_games',
    'List_of_Games_for_Windows_–_Live_titles',
    'List_of_Kaypro_games',
    'List_of_games_with_OpenGL_support',
    'List_of_games_with_Vulkan_support',
    'List_of_Linux_games',
    'List_of_PC_games',
    'List_of_games_with_DirectX_11_support',
    'List_of_games_with_DirectX_12_support',
    'List_of_Games_for_Windows_titles',
    'List_of_Xbox_System_Link_games',
    'List_of_MSX_games',
    'List of Xbox Live Arcade games',
    'List_of_Xbox_games',
    'List_of_Xbox_360_games',
    'List_of_Xbox_One_games',
    'List_of_Xbox_360_System_Link_games',
    'List_of_Xbox_games_on_Windows_Phone',
    'List of Xbox games compatible with Xbox 360',
    'List_of_PC_Engine_games',
    'List_of_Family_Computer_games',
    'List_of_Family_Computer_Disk_System_games',
    'List_of_GameCube_games',
    'List_of_Nintendo_64_games',
    'List_of_Nintendo_Entertainment_System_games',
    'List_of_Nintendo_Switch_games',
    'List_of_Satellaview_broadcasts',
    'List_of_Super_Famicom_games',
    'List_of_Super_Nintendo_Entertainment_System_games',
    'List_of_Wii_games',
    'List_of_Wii_games_on_Wii_U_eShop',
    'List_of_Wii_U_games',
    'List_of_Virtual_Boy_games',
    'List_of_WiiWare_games',
    'List_of_Game_Boy_Color_games',
    'List_of_Game_Boy_Advance_games',
    'List_of_Nintendo_DS_games',
    'List_of_Nintendo_3DS_games',
    'List_of_DSiWare_games_and_applications',
    'List of Game Gear games',
    'List of Sega arcade video games',
    'List of Dreamcast games',
    'List of Sega mobile games',
    'List of 32X games',
    'List_of_ZX_Spectrum_games',
    'List_of_Neo_Geo_games',
    'List_of_Neo_Geo_Pocket_Color_games',
    'List_of_PlayStation_games_(A–L)',
    'List_of_PlayStation_games_(M–Z)',
    'List_of_PlayStation_2_games',
    'List of PlayStation Store games',
    'High-definition remasters for PlayStation consoles',
    'List of PlayStation 3 games released on disc',
    'List of download-only PlayStation 3 games',
    'List_of_PlayStation_4_games',
    'List_of_PlayStation_4_games_(M-Z)',
    'List_of_PlayStation_Portable_games',
    'List_of_PlayStation_Move_games',
    'List_of_Sony_Pictures_mobile_games',
    'List of 3DO Interactive Multiplayer games',
    'List of PC booter games',
    'List_of_ColecoVision_games',
    'List_of_Gizmondo_games',
    'List_of_commercial_GP32_games',
    'List_of_HP3000_games',
    'List_of_Intellivision_games',
    'List of Ouya software#Games',
    'List_of_pinball_machines',
    'Tapwave Zodiac#Games',
    'List_of_Vectrex_games',
    'List_of_Activision_video_games',
    'List_of_Astragon_games',
    'Blizzard Entertainment#Games',
    'List of Capcom games: 0–D',
    'List of Capcom games: E–L',
    'List of Capcom games: N–R',
    'List of Capcom games: T–Z',
    'List_of_Codemasters_video_games',
    'List of Master System games',
    'List_of_Electronic_Arts_games',
    'List of Enix games',
    'List_of_Destination_Software_games',
    'List_of_Konami_games',
    'List_of_LucasArts_games',
    'List_of_Namco_games',
    'Mojang#Games',
    'List_of_Nintendo_products',
    'List_of_Sierra_Entertainment_video_games',
    'List_of_SNK_games',
    'List_of_Square_video_games',
    'List_of_Square_Enix_video_games',
    'List_of_Taito_games',
    'List_of_THQ_games',
    'List_of_Ubisoft_games',
    'List_of_Zushi_Games_games',
    'CI_Games#List_of_games',
    'List_of_video_game_franchises',
    'Bemani',
    'List_of_Beatmania_video_games',
    'List_of_Bomberman_video_games',
    'List_of_Castlevania_media',
    'List_of_Dance_Dance_Revolution_video_games',
    'List_of_Digimon_video_games',
    'List_of_Donkey_Kong_video_games',
    'List_of_Final_Fantasy_video_games',
    'List_of_Final_Fantasy_media',
    'List_of_Kirby_media',
    'List_of_Metroid_media',
    'List_of_Mortal_Kombat_media',
    'List_of_Star_Wars_video_games',
    'List_of_Story_of_Seasons_video_games',
    'List_of_Wario_video_games',
    'List of Sega Genesis games',
    'List_of_video_games_developed_in_the_Czech_Republic',
    'List_of_video_games_developed_in_the_Netherlands',
    'List of Source mods',
    'List of Unity games',
    'List_of_Unreal_Engine_games',
    'List of gun games',
    'List_of_CryEngine_games',
    'List_of_fighting_games',
    'List of gun games',
    'List_of_platform_game_series',
    'List_of_party_video_games',
    'List_of_puzzle_video_games',
    'List_of_maze_video_games',
    'List_of_Tetris_variants',
    'List_of_quiz_arcade_games',
    'List_of_roguelikes',
    'List_of_business_simulation_video_games',
    'List_of_god_video_games',
    'List_of_simulation_video_games',
    'List_of_space_flight_simulator_games',
    'List_of_baseball_video_games',
    'List of American football video games',
    'List of association football video games',
    'Formula One video games',
    'List_of_golf_video_games',
    'List_of_volleyball_video_games',
    'List_of_4X_video_games',
    'List_of_artillery_video_games',
    'List_of_grand_strategy_video_games',
    'List_of_massively_multiplayer_online_strategy_video_games',
    'List_of_multiplayer_online_battle_arena_games',
    'List_of_erotic_video_games',
    'List_of_eroge',
    'List_of_arcade_video_games:_0..9',
    'List_of_arcade_video_games:_A',
    'List_of_arcade_video_games:_B',
    'List_of_arcade_video_games:_C',
    'List_of_arcade_video_games:_D',
    'List_of_arcade_video_games:_E',
    'List_of_arcade_video_games:_F',
    'List_of_arcade_video_games:_G',
    'List_of_arcade_video_games:_H',
    'List_of_arcade_video_games:_I',
    'List_of_arcade_video_games:_J',
    'List_of_arcade_video_games:_K',
    'List_of_arcade_video_games:_L',
    'List_of_arcade_video_games:_M',
    'List_of_arcade_video_games:_N',
    'List_of_arcade_video_games:_O',
    'List_of_arcade_video_games:_P',
    'List_of_arcade_video_games:_Q',
    'List_of_arcade_video_games:_R',
    'List_of_arcade_video_games:_S',
    'List_of_arcade_video_games:_T',
    'List_of_arcade_video_games:_U',
    'List_of_arcade_video_games:_V',
    'List_of_arcade_video_games:_X',
    'List_of_arcade_video_games:_Y',
    'List_of_arcade_video_games:_Z',
    'List_of_arcade_video_games:_W',
    'List_of_Christian_video_games',
    'List_of_horror_video_games',
    'List_of_freeware_video_games',
    'List_of_commercial_video_games_released_as_freeware',
    'List_of_commercial_video_games_with_available_source_code',
    'List_of_banned_video_games',
    'List_of_commercial_failures_in_video_gaming',
    'List_of_video_games_notable_for_negative_reception',
    'List_of_vaporware',
    'List_of_video_game_collector_and_limited_editions',
    'List_of_video_games_based_on_anime_or_manga',
    'List_of_video_games_notable_for_speedrunning',
    'List_of_video_games_in_the_Museum_of_Modern_Art',
    'Index_of_DOS_games_(0–9)',
    'Index_of_DOS_games_(A)',
    'Index_of_DOS_games_(B)',
    'Index_of_DOS_games_(C)',
    'Index_of_DOS_games_(D)',
    'Index_of_DOS_games_(E)',
    'Index_of_DOS_games_(F)',
    'Index_of_DOS_games_(G)',
    'Index_of_DOS_games_(H)',
    'Index_of_DOS_games_(I)',
    'Index_of_DOS_games_(J)',
    'Index_of_DOS_games_(K)',
    'Index_of_DOS_games_(L)',
    'Index_of_DOS_games_(M)',
    'Index_of_DOS_games_(N)',
    'Index_of_DOS_games_(O)',
    'Index_of_DOS_games_(P)',
    'Index_of_DOS_games_(Q)',
    'Index_of_DOS_games_(R)',
    'Index_of_DOS_games_(S)',
    'Index_of_DOS_games_(T)',
    'Index_of_DOS_games_(U)',
    'Index_of_DOS_games_(V)',
    'Index_of_DOS_games_(X)',
    'Index_of_DOS_games_(Y)',
    'Index_of_DOS_games_(Z)',
    'Index_of_Windows_games_(0–9)',
    'Index_of_Windows_games_(A)',
    'Index_of_Windows_games_(B)',
    'Index_of_Windows_games_(C)',
    'Index_of_Windows_games_(D)',
    'Index_of_Windows_games_(E)',
    'Index_of_Windows_games_(F)',
    'Index_of_Windows_games_(G)',
    'Index_of_Windows_games_(H)',
    'Index_of_Windows_games_(I)',
    'Index_of_Windows_games_(J)',
    'Index_of_Windows_games_(K)',
    'Index_of_Windows_games_(L)',
    'Index_of_Windows_games_(M)',
    'Index_of_Windows_games_(N)',
    'Index_of_Windows_games_(O)',
    'Index_of_Windows_games_(P)',
    'Index_of_Windows_games_(Q)',
    'Index_of_Windows_games_(R)',
    'Index_of_Windows_games_(S)',
    'Index_of_Windows_games_(T)',
    'Index_of_Windows_games_(U)',
    'Index_of_Windows_games_(V)',
    'Index_of_Windows_games_(X)',
    'Index_of_Windows_games_(Y)',
    'Index_of_Windows_games_(Z)',
    'List_of_PlayStation_Vita_games_(A–L)',
    'List_of_PlayStation_Vita_games_(M–Z)',
    'List_of_PC_games_(B)',
    'List_of_PC_games_(C)',
    'List_of_PC_games_(D)',
    'List_of_PC_games_(E)',
    'List_of_PC_games_(F)',
    'List_of_PC_games_(G)',
    'List_of_PC_games_(H)',
    'List_of_PC_games_(I)',
    'List_of_PC_games_(J)',
    'List_of_PC_games_(K)',
    'List_of_PC_games_(L)',
    'List_of_PC_games_(M)',
    'List_of_PC_games_(N)',
    'List_of_PC_games_(O)',
    'List_of_PC_games_(P)',
    'List_of_PC_games_(Q)',
    'List_of_PC_games_(R)',
    'List_of_PC_games_(S)',
    'List_of_PC_games_(T)',
    'List_of_PC_games_(U)',
    'List_of_PC_games_(V)',
    'List_of_PC_games_(X)',
    'List_of_PC_games_(Y)',
    'List_of_PC_games_(Z)',
    'List_of_PC_games_(Numerical)',
    'List_of_Windows_3.x_games',
    'List_of_Atari_5200_games',
    'List_of_Virtual_Console_games_for_Wii_(Japan)',
    'List_of_Virtual_Console_games_for_Wii_U_(Japan)',
    'List_of_Virtual_Console_games_for_Wii_U_(North_America)',
    'List_of_Virtual_Console_games_for_Wii_(North_America)',
    'List_of_Virtual_Console_games_for_Nintendo_3DS_(PAL_region)',
    'List_of_Virtual_Console_games_for_Nintendo_3DS_(Japan)',
    'List_of_Virtual_Console_games_for_Nintendo_3DS_(North_America)',
    'List_of_Virtual_Console_games_for_Wii_(PAL_region)',
    'List_of_DSiWare_games_and_applications',
    'List of Magnavox Odyssey² games',
    'List of Sega CD games',
]


DESIRED_PLATFORMS = NEW_LISTS


# scrap article outcome
class ArticleOutcome:
    FOUND_NOT = -1
    FOUND_UAT = 0
    FOUND_ASSERTIVE = 1
    NO_INFOBOX_ARTICLE = 2


ARTICLE_OUTCOME_DISPLAY = {
    ArticleOutcome.FOUND_NOT: "FOUND_NOT",
    ArticleOutcome.FOUND_UAT: "FOUND_UAT",
    ArticleOutcome.FOUND_ASSERTIVE: "FOUND_ASSERTIVE",
    ArticleOutcome.NO_INFOBOX_ARTICLE: "NO INFOBOX BUT ASSERTIVE",
}


class UnassertiveArticle:
    WRONG_ARTICLE = 0
    CROSS_MEDIA_ARTICLE = 1
    GAME_SERIES_ARTICLE = 2
    NO_INFOBOX_ARTICLE = 3
    CONFIRMED_BAD_LEAD = 4

UAT_DISPLAY = {
    UnassertiveArticle.WRONG_ARTICLE: "WRONG_ARTICLE",
    UnassertiveArticle.CONFIRMED_BAD_LEAD: "CONFIRMED_BAD_LEAD",
    UnassertiveArticle.CROSS_MEDIA_ARTICLE: "Cross-Media Article",
    UnassertiveArticle.GAME_SERIES_ARTICLE: "Game-Series Article",
    UnassertiveArticle.NO_INFOBOX_ARTICLE: "No Infobox Game Article",
}
